// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAffix: typeof import('@arco-design/web-vue')['Affix'];
    AAlert: typeof import('@arco-design/web-vue')['Alert'];
    AAvatar: typeof import('@arco-design/web-vue')['Avatar'];
    ABreadcrumb: typeof import('@arco-design/web-vue')['Breadcrumb'];
    ABreadcrumbItem: typeof import('@arco-design/web-vue')['BreadcrumbItem'];
    AButton: typeof import('@arco-design/web-vue')['Button'];
    ACard: typeof import('@arco-design/web-vue')['Card'];
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox'];
    ACol: typeof import('@arco-design/web-vue')['Col'];
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider'];
    ADoption: typeof import('@arco-design/web-vue')['Doption'];
    ADrawer: typeof import('@arco-design/web-vue')['Drawer'];
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown'];
    AForm: typeof import('@arco-design/web-vue')['Form'];
    AFormItem: typeof import('@arco-design/web-vue')['FormItem'];
    AInput: typeof import('@arco-design/web-vue')['Input'];
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber'];
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword'];
    ALayout: typeof import('@arco-design/web-vue')['Layout'];
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent'];
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter'];
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider'];
    ALink: typeof import('@arco-design/web-vue')['Link'];
    AMenu: typeof import('@arco-design/web-vue')['Menu'];
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem'];
    AOption: typeof import('@arco-design/web-vue')['Option'];
    AResult: typeof import('@arco-design/web-vue')['Result'];
    ARow: typeof import('@arco-design/web-vue')['Row'];
    ASelect: typeof import('@arco-design/web-vue')['Select'];
    ASpace: typeof import('@arco-design/web-vue')['Space'];
    ASpin: typeof import('@arco-design/web-vue')['Spin'];
    AStep: typeof import('@arco-design/web-vue')['Step'];
    ASteps: typeof import('@arco-design/web-vue')['Steps'];
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu'];
    ASwitch: typeof import('@arco-design/web-vue')['Switch'];
    ATable: typeof import('@arco-design/web-vue')['Table'];
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip'];
    ATypographyTitle: typeof import('@arco-design/web-vue')['TypographyTitle'];
    AUpload: typeof import('@arco-design/web-vue')['Upload'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
